// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb0T68SQGKmzBKhisS6geWfQO8M5ujOd8',
    appId: '1:638470781836:web:805086b212989347cc34a9',
    messagingSenderId: '638470781836',
    projectId: 'subzero-4c049',
    authDomain: 'subzero-4c049.firebaseapp.com',
    storageBucket: 'subzero-4c049.firebasestorage.app',
    measurementId: 'G-YWVC961HNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCUWPhMGGz-W81A_nhEIuSvpYXrccazFU',
    appId: '1:638470781836:android:60e611cc1207f589cc34a9',
    messagingSenderId: '638470781836',
    projectId: 'subzero-4c049',
    storageBucket: 'subzero-4c049.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuVWWeLfHUwf8szPSnso4fjIoTUI5k8VU',
    appId: '1:638470781836:ios:2a38b282f24d7918cc34a9',
    messagingSenderId: '638470781836',
    projectId: 'subzero-4c049',
    storageBucket: 'subzero-4c049.firebasestorage.app',
    iosBundleId: 'com.example.appFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuVWWeLfHUwf8szPSnso4fjIoTUI5k8VU',
    appId: '1:638470781836:ios:2a38b282f24d7918cc34a9',
    messagingSenderId: '638470781836',
    projectId: 'subzero-4c049',
    storageBucket: 'subzero-4c049.firebasestorage.app',
    iosBundleId: 'com.example.appFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb0T68SQGKmzBKhisS6geWfQO8M5ujOd8',
    appId: '1:638470781836:web:97d1c2337b8cc29fcc34a9',
    messagingSenderId: '638470781836',
    projectId: 'subzero-4c049',
    authDomain: 'subzero-4c049.firebaseapp.com',
    storageBucket: 'subzero-4c049.firebasestorage.app',
    measurementId: 'G-MH1KSNWERW',
  );
}
